# Generated by Django 2.2.1 on 2019-05-16 18:40
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0003_auto_20190514_1650"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="description",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
