# Generated by Django 2.2.1 on 2019-05-16 18:43
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0004_auto_20190516_1840"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Task",
        ),
    ]
